// Generated by scripts/sync-webllm-models.cjs from @mlc-ai/web-llm.
// Run `bun run models:sync` after upgrading @mlc-ai/web-llm.

export interface OfficialLocalModelOption {
  id: string;
  vram: number | null;
  context: number | null;
}

export const OFFICIAL_LOCAL_MODELS: OfficialLocalModelOption[] = [
  {
    "id": "snowflake-arctic-embed-s-q0f32-MLC-b4",
    "vram": 238.71,
    "context": null
  },
  {
    "id": "SmolLM2-135M-Instruct-q0f16-MLC",
    "vram": 359.69,
    "context": 4096
  },
  {
    "id": "SmolLM2-360M-Instruct-q4f16_1-MLC",
    "vram": 376.06,
    "context": 4096
  },
  {
    "id": "snowflake-arctic-embed-m-q0f32-MLC-b4",
    "vram": 539.4,
    "context": null
  },
  {
    "id": "SmolLM2-360M-Instruct-q4f32_1-MLC",
    "vram": 579.61,
    "context": 4096
  },
  {
    "id": "TinyLlama-1.1B-Chat-v0.4-q4f16_1-MLC-1k",
    "vram": 675.24,
    "context": 1024
  },
  {
    "id": "TinyLlama-1.1B-Chat-v1.0-q4f16_1-MLC-1k",
    "vram": 675.24,
    "context": 1024
  },
  {
    "id": "TinyLlama-1.1B-Chat-v0.4-q4f16_1-MLC",
    "vram": 697.24,
    "context": 2048
  },
  {
    "id": "TinyLlama-1.1B-Chat-v1.0-q4f16_1-MLC",
    "vram": 697.24,
    "context": 2048
  },
  {
    "id": "SmolLM2-135M-Instruct-q0f32-MLC",
    "vram": 719.38,
    "context": 4096
  },
  {
    "id": "TinyLlama-1.1B-Chat-v0.4-q4f32_1-MLC-1k",
    "vram": 795.98,
    "context": 1024
  },
  {
    "id": "TinyLlama-1.1B-Chat-v1.0-q4f32_1-MLC-1k",
    "vram": 795.98,
    "context": 1024
  },
  {
    "id": "TinyLlama-1.1B-Chat-v0.4-q4f32_1-MLC",
    "vram": 839.98,
    "context": 2048
  },
  {
    "id": "TinyLlama-1.1B-Chat-v1.0-q4f32_1-MLC",
    "vram": 839.98,
    "context": 2048
  },
  {
    "id": "SmolLM2-360M-Instruct-q0f16-MLC",
    "vram": 871.99,
    "context": 4096
  },
  {
    "id": "Llama-3.2-1B-Instruct-q4f16_1-MLC",
    "vram": 879.04,
    "context": 4096
  },
  {
    "id": "Qwen2-0.5B-Instruct-q4f16_1-MLC",
    "vram": 944.62,
    "context": 4096
  },
  {
    "id": "Qwen2.5-0.5B-Instruct-q4f16_1-MLC",
    "vram": 944.62,
    "context": 4096
  },
  {
    "id": "Qwen2.5-Coder-0.5B-Instruct-q4f16_1-MLC",
    "vram": 944.62,
    "context": 4096
  },
  {
    "id": "snowflake-arctic-embed-s-q0f32-MLC-b32",
    "vram": 1022.82,
    "context": null
  },
  {
    "id": "Qwen2.5-0.5B-Instruct-q4f32_1-MLC",
    "vram": 1060.2,
    "context": 4096
  },
  {
    "id": "Qwen2.5-Coder-0.5B-Instruct-q4f32_1-MLC",
    "vram": 1060.2,
    "context": 4096
  },
  {
    "id": "Llama-3.2-1B-Instruct-q4f32_1-MLC",
    "vram": 1128.82,
    "context": 4096
  },
  {
    "id": "phi-1_5-q4f16_1-MLC",
    "vram": 1210.09,
    "context": 2048
  },
  {
    "id": "phi-1_5-q4f16_1-MLC-1k",
    "vram": 1210.09,
    "context": 1024
  },
  {
    "id": "Qwen3-0.6B-q4f16_1-MLC",
    "vram": 1403.34,
    "context": 4096
  },
  {
    "id": "snowflake-arctic-embed-m-q0f32-MLC-b32",
    "vram": 1407.51,
    "context": null
  },
  {
    "id": "gemma-2b-it-q4f16_1-MLC",
    "vram": 1476.52,
    "context": 4096
  },
  {
    "id": "gemma-2b-it-q4f16_1-MLC-1k",
    "vram": 1476.52,
    "context": 1024
  },
  {
    "id": "stablelm-2-zephyr-1_6b-q4f16_1-MLC-1k",
    "vram": 1511.66,
    "context": 1024
  },
  {
    "id": "gemma-2-2b-it-q4f16_1-MLC-1k",
    "vram": 1583.3,
    "context": 1024
  },
  {
    "id": "Qwen2-0.5B-Instruct-q0f16-MLC",
    "vram": 1624.12,
    "context": 4096
  },
  {
    "id": "Qwen2.5-0.5B-Instruct-q0f16-MLC",
    "vram": 1624.12,
    "context": 4096
  },
  {
    "id": "Qwen2.5-Coder-0.5B-Instruct-q0f16-MLC",
    "vram": 1624.12,
    "context": 4096
  },
  {
    "id": "Qwen2-1.5B-Instruct-q4f16_1-MLC",
    "vram": 1629.75,
    "context": 4096
  },
  {
    "id": "Qwen2-Math-1.5B-Instruct-q4f16_1-MLC",
    "vram": 1629.75,
    "context": 4096
  },
  {
    "id": "Qwen2.5-1.5B-Instruct-q4f16_1-MLC",
    "vram": 1629.75,
    "context": 4096
  },
  {
    "id": "Qwen2.5-Coder-1.5B-Instruct-q4f16_1-MLC",
    "vram": 1629.75,
    "context": 4096
  },
  {
    "id": "Qwen2.5-Math-1.5B-Instruct-q4f16_1-MLC",
    "vram": 1629.75,
    "context": 4096
  },
  {
    "id": "phi-1_5-q4f32_1-MLC",
    "vram": 1682.09,
    "context": 2048
  },
  {
    "id": "phi-1_5-q4f32_1-MLC-1k",
    "vram": 1682.09,
    "context": 1024
  },
  {
    "id": "SmolLM2-360M-Instruct-q0f32-MLC",
    "vram": 1743.99,
    "context": 4096
  },
  {
    "id": "gemma-2b-it-q4f32_1-MLC",
    "vram": 1750.66,
    "context": 4096
  },
  {
    "id": "gemma-2b-it-q4f32_1-MLC-1k",
    "vram": 1750.66,
    "context": 1024
  },
  {
    "id": "SmolLM2-1.7B-Instruct-q4f16_1-MLC",
    "vram": 1774.19,
    "context": 4096
  },
  {
    "id": "stablelm-2-zephyr-1_6b-q4f32_1-MLC-1k",
    "vram": 1847.33,
    "context": 1024
  },
  {
    "id": "gemma-2-2b-it-q4f32_1-MLC-1k",
    "vram": 1884.75,
    "context": 1024
  },
  {
    "id": "Qwen2-1.5B-Instruct-q4f32_1-MLC",
    "vram": 1888.97,
    "context": 4096
  },
  {
    "id": "Qwen2-Math-1.5B-Instruct-q4f32_1-MLC",
    "vram": 1888.97,
    "context": 4096
  },
  {
    "id": "Qwen2.5-1.5B-Instruct-q4f32_1-MLC",
    "vram": 1888.97,
    "context": 4096
  },
  {
    "id": "Qwen2.5-Coder-1.5B-Instruct-q4f32_1-MLC",
    "vram": 1888.97,
    "context": 4096
  },
  {
    "id": "Qwen2.5-Math-1.5B-Instruct-q4f32_1-MLC",
    "vram": 1888.97,
    "context": 4096
  },
  {
    "id": "gemma-2-2b-it-q4f16_1-MLC",
    "vram": 1895.3,
    "context": 4096
  },
  {
    "id": "gemma-2-2b-jpn-it-q4f16_1-MLC",
    "vram": 1895.3,
    "context": 4096
  },
  {
    "id": "Qwen3-0.6B-q4f32_1-MLC",
    "vram": 1924.98,
    "context": 4096
  },
  {
    "id": "Qwen3-1.7B-q4f16_1-MLC",
    "vram": 2036.66,
    "context": 4096
  },
  {
    "id": "RedPajama-INCITE-Chat-3B-v1-q4f16_1-MLC-1k",
    "vram": 2041.09,
    "context": 1024
  },
  {
    "id": "stablelm-2-zephyr-1_6b-q4f16_1-MLC",
    "vram": 2087.66,
    "context": 4096
  },
  {
    "id": "phi-2-q4f16_1-MLC-1k",
    "vram": 2131.97,
    "context": 1024
  },
  {
    "id": "Qwen3-0.6B-q0f16-MLC",
    "vram": 2220.38,
    "context": 4096
  },
  {
    "id": "Hermes-3-Llama-3.2-3B-q4f16_1-MLC",
    "vram": 2263.69,
    "context": 4096
  },
  {
    "id": "Llama-3.2-3B-Instruct-q4f16_1-MLC",
    "vram": 2263.69,
    "context": 4096
  },
  {
    "id": "Qwen2.5-3B-Instruct-q4f16_1-MLC",
    "vram": 2504.76,
    "context": 4096
  },
  {
    "id": "Qwen2.5-Coder-3B-Instruct-q4f16_1-MLC",
    "vram": 2504.76,
    "context": 4096
  },
  {
    "id": "gemma-2-2b-it-q4f32_1-MLC",
    "vram": 2508.75,
    "context": 4096
  },
  {
    "id": "gemma-2-2b-jpn-it-q4f32_1-MLC",
    "vram": 2508.75,
    "context": 4096
  },
  {
    "id": "Phi-3-mini-4k-instruct-q4f16_1-MLC-1k",
    "vram": 2520.07,
    "context": 1024
  },
  {
    "id": "Phi-3.5-mini-instruct-q4f16_1-MLC-1k",
    "vram": 2520.07,
    "context": 1024
  },
  {
    "id": "RedPajama-INCITE-Chat-3B-v1-q4f32_1-MLC-1k",
    "vram": 2558.09,
    "context": 1024
  },
  {
    "id": "Llama-3.2-1B-Instruct-q0f16-MLC",
    "vram": 2573.13,
    "context": 4096
  },
  {
    "id": "Qwen3-1.7B-q4f32_1-MLC",
    "vram": 2635.44,
    "context": 4096
  },
  {
    "id": "SmolLM2-1.7B-Instruct-q4f32_1-MLC",
    "vram": 2692.38,
    "context": 4096
  },
  {
    "id": "phi-2-q4f32_1-MLC-1k",
    "vram": 2740.48,
    "context": 1024
  },
  {
    "id": "Qwen2.5-3B-Instruct-q4f32_1-MLC",
    "vram": 2893.64,
    "context": 4096
  },
  {
    "id": "Qwen2.5-Coder-3B-Instruct-q4f32_1-MLC",
    "vram": 2893.64,
    "context": 4096
  },
  {
    "id": "Hermes-3-Llama-3.2-3B-q4f32_1-MLC",
    "vram": 2951.51,
    "context": 4096
  },
  {
    "id": "Llama-3.2-3B-Instruct-q4f32_1-MLC",
    "vram": 2951.51,
    "context": 4096
  },
  {
    "id": "RedPajama-INCITE-Chat-3B-v1-q4f16_1-MLC",
    "vram": 2972.09,
    "context": 2048
  },
  {
    "id": "stablelm-2-zephyr-1_6b-q4f32_1-MLC",
    "vram": 2999.33,
    "context": 4096
  },
  {
    "id": "phi-2-q4f16_1-MLC",
    "vram": 3053.97,
    "context": 2048
  },
  {
    "id": "Phi-3-mini-4k-instruct-q4f32_1-MLC-1k",
    "vram": 3179.12,
    "context": 1024
  },
  {
    "id": "Phi-3.5-mini-instruct-q4f32_1-MLC-1k",
    "vram": 3179.12,
    "context": 1024
  },
  {
    "id": "Qwen3-4B-q4f16_1-MLC",
    "vram": 3431.59,
    "context": 4096
  },
  {
    "id": "Phi-3-mini-4k-instruct-q4f16_1-MLC",
    "vram": 3672.07,
    "context": 4096
  },
  {
    "id": "Phi-3.5-mini-instruct-q4f16_1-MLC",
    "vram": 3672.07,
    "context": 4096
  },
  {
    "id": "RedPajama-INCITE-Chat-3B-v1-q4f32_1-MLC",
    "vram": 3928.09,
    "context": 2048
  },
  {
    "id": "Phi-3.5-vision-instruct-q4f16_1-MLC",
    "vram": 3952.18,
    "context": 4096
  },
  {
    "id": "phi-2-q4f32_1-MLC",
    "vram": 4032.48,
    "context": 2048
  },
  {
    "id": "Hermes-2-Pro-Mistral-7B-q4f16_1-MLC",
    "vram": 4033.28,
    "context": 4096
  },
  {
    "id": "Qwen3-4B-q4f32_1-MLC",
    "vram": 4327.71,
    "context": 4096
  },
  {
    "id": "Mistral-7B-Instruct-v0.2-q4f16_1-MLC",
    "vram": 4573.39,
    "context": 4096
  },
  {
    "id": "Mistral-7B-Instruct-v0.3-q4f16_1-MLC",
    "vram": 4573.39,
    "context": 4096
  },
  {
    "id": "NeuralHermes-2.5-Mistral-7B-q4f16_1-MLC",
    "vram": 4573.39,
    "context": 4096
  },
  {
    "id": "OpenHermes-2.5-Mistral-7B-q4f16_1-MLC",
    "vram": 4573.39,
    "context": 4096
  },
  {
    "id": "WizardMath-7B-V1.1-q4f16_1-MLC",
    "vram": 4573.39,
    "context": 4096
  },
  {
    "id": "Llama-3-8B-Instruct-q4f16_1-MLC-1k",
    "vram": 4598.34,
    "context": 1024
  },
  {
    "id": "Llama-3.1-8B-Instruct-q4f16_1-MLC-1k",
    "vram": 4598.34,
    "context": 1024
  },
  {
    "id": "Llama-2-7b-chat-hf-q4f16_1-MLC-1k",
    "vram": 4618.52,
    "context": 1024
  },
  {
    "id": "Hermes-3-Llama-3.1-8B-q4f16_1-MLC",
    "vram": 4876.13,
    "context": 4096
  },
  {
    "id": "Hermes-2-Pro-Llama-3-8B-q4f16_1-MLC",
    "vram": 4976.13,
    "context": 4096
  },
  {
    "id": "Hermes-2-Theta-Llama-3-8B-q4f16_1-MLC",
    "vram": 4976.13,
    "context": 4096
  },
  {
    "id": "DeepSeek-R1-Distill-Llama-8B-q4f16_1-MLC",
    "vram": 5001,
    "context": 4096
  },
  {
    "id": "Llama-3-8B-Instruct-q4f16_1-MLC",
    "vram": 5001,
    "context": 4096
  },
  {
    "id": "Llama-3.1-8B-Instruct-q4f16_1-MLC",
    "vram": 5001,
    "context": 4096
  },
  {
    "id": "DeepSeek-R1-Distill-Qwen-7B-q4f16_1-MLC",
    "vram": 5106.67,
    "context": 4096
  },
  {
    "id": "Qwen2-7B-Instruct-q4f16_1-MLC",
    "vram": 5106.67,
    "context": 4096
  },
  {
    "id": "Qwen2-Math-7B-Instruct-q4f16_1-MLC",
    "vram": 5106.67,
    "context": 4096
  },
  {
    "id": "Qwen2.5-7B-Instruct-q4f16_1-MLC",
    "vram": 5106.67,
    "context": 4096
  },
  {
    "id": "Qwen2.5-Coder-7B-Instruct-q4f16_1-MLC",
    "vram": 5106.67,
    "context": 4096
  },
  {
    "id": "Llama-2-7b-chat-hf-q4f32_1-MLC-1k",
    "vram": 5284.01,
    "context": 1024
  },
  {
    "id": "Llama-3-8B-Instruct-q4f32_1-MLC-1k",
    "vram": 5295.7,
    "context": 1024
  },
  {
    "id": "Llama-3.1-8B-Instruct-q4f32_1-MLC-1k",
    "vram": 5295.7,
    "context": 1024
  },
  {
    "id": "Phi-3-mini-4k-instruct-q4f32_1-MLC",
    "vram": 5483.12,
    "context": 4096
  },
  {
    "id": "Phi-3.5-mini-instruct-q4f32_1-MLC",
    "vram": 5483.12,
    "context": 4096
  },
  {
    "id": "Mistral-7B-Instruct-v0.3-q4f32_1-MLC",
    "vram": 5619.27,
    "context": 4096
  },
  {
    "id": "Qwen3-8B-q4f16_1-MLC",
    "vram": 5695.78,
    "context": 4096
  },
  {
    "id": "Hermes-3-Llama-3.1-8B-q4f32_1-MLC",
    "vram": 5779.27,
    "context": 4096
  },
  {
    "id": "Phi-3.5-vision-instruct-q4f32_1-MLC",
    "vram": 5879.84,
    "context": 4096
  },
  {
    "id": "DeepSeek-R1-Distill-Qwen-7B-q4f32_1-MLC",
    "vram": 5900.09,
    "context": 4096
  },
  {
    "id": "Qwen2-7B-Instruct-q4f32_1-MLC",
    "vram": 5900.09,
    "context": 4096
  },
  {
    "id": "Qwen2-Math-7B-Instruct-q4f32_1-MLC",
    "vram": 5900.09,
    "context": 4096
  },
  {
    "id": "Qwen2.5-7B-Instruct-q4f32_1-MLC",
    "vram": 5900.09,
    "context": 4096
  },
  {
    "id": "Qwen2.5-Coder-7B-Instruct-q4f32_1-MLC",
    "vram": 5900.09,
    "context": 4096
  },
  {
    "id": "Hermes-2-Pro-Llama-3-8B-q4f32_1-MLC",
    "vram": 6051.27,
    "context": 4096
  },
  {
    "id": "Hermes-2-Theta-Llama-3-8B-q4f32_1-MLC",
    "vram": 6051.27,
    "context": 4096
  },
  {
    "id": "DeepSeek-R1-Distill-Llama-8B-q4f32_1-MLC",
    "vram": 6101.01,
    "context": 4096
  },
  {
    "id": "Llama-3-8B-Instruct-q4f32_1-MLC",
    "vram": 6101.01,
    "context": 4096
  },
  {
    "id": "Llama-3.1-8B-Instruct-q4f32_1-MLC",
    "vram": 6101.01,
    "context": 4096
  },
  {
    "id": "gemma-2-9b-it-q4f16_1-MLC",
    "vram": 6422.01,
    "context": 4096
  },
  {
    "id": "Llama-2-7b-chat-hf-q4f16_1-MLC",
    "vram": 6749.02,
    "context": 4096
  },
  {
    "id": "Qwen3-8B-q4f32_1-MLC",
    "vram": 6852.55,
    "context": 4096
  },
  {
    "id": "gemma-2-9b-it-q4f32_1-MLC",
    "vram": 8383.33,
    "context": 4096
  },
  {
    "id": "Llama-2-7b-chat-hf-q4f32_1-MLC",
    "vram": 9109.03,
    "context": 4096
  },
  {
    "id": "Llama-2-13b-chat-hf-q4f16_1-MLC",
    "vram": 11814.09,
    "context": 4096
  },
  {
    "id": "Llama-3-70B-Instruct-q3f16_1-MLC",
    "vram": 31153.13,
    "context": 4096
  },
  {
    "id": "Llama-3.1-70B-Instruct-q3f16_1-MLC",
    "vram": 31153.13,
    "context": 4096
  },
  {
    "id": "Ministral-3-3B-Base-2512-q4f16_1-MLC",
    "vram": null,
    "context": 4096
  },
  {
    "id": "Ministral-3-3B-Instruct-2512-BF16-q4f16_1-MLC",
    "vram": null,
    "context": 4096
  },
  {
    "id": "Ministral-3-3B-Reasoning-2512-q4f16_1-MLC",
    "vram": null,
    "context": 4096
  }
];
